FROM postgres:16
ENV POSTGRES_USER=testuser
ENV POSTGRES_PASSWORD=testpassword

# Copy pre-built Linux binary from host (much faster!)
# Make sure to run 'make build-linux' first
COPY bin/pgqueue4go-linux /usr/local/bin/pgqueue4go

# Copy the database setup script  
COPY --chmod=0755 test/docker/init_test_db.sh /docker-entrypoint-initdb.d/init_test_db.sh